// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-x52vyl8sHEBNQairzvxrkvEr6oZer0',
    appId: '1:611994389857:web:1500bd0bae5089f898c920',
    messagingSenderId: '611994389857',
    projectId: 'dictionaryentoen',
    authDomain: 'dictionaryentoen.firebaseapp.com',
    storageBucket: 'dictionaryentoen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkIVR2GErwgo6PZeCNX1AKNT8z_r2vnI',
    appId: '1:611994389857:android:74e862aedb6a9d9f98c920',
    messagingSenderId: '611994389857',
    projectId: 'dictionaryentoen',
    storageBucket: 'dictionaryentoen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6IRbL0RyYDxItgucEUq0iOEfk_-XOAPw',
    appId: '1:611994389857:ios:38758b8b17316f0e98c920',
    messagingSenderId: '611994389857',
    projectId: 'dictionaryentoen',
    storageBucket: 'dictionaryentoen.appspot.com',
    iosClientId: '611994389857-g65kf34de53resqj1rv56pg9plquvqqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionaryEnToEn',
  );
}
